# Introduccion

* pandas es una libreria diseñada para tareas de analisis y manipulacion de datos
* Orientado al manejo de datos de caracter tabular, como:
    * las hojas de calculo 
    * Bases de datos relacionales
* Su funcionalidad gira en torno a dos estructuras de datos fundamentales:
    * `Series`: 
        * Arreglo unidimensional de datos, cuyos elementos son identificados por un indice (no necesariamente unico como de los diccionarios)
        * Se pueden considerar como dos arreglos de NumPy asociados:
            * El indice de la serie -> sus valores corresponden a los valores usados para identificar cada entrada de la serie.
            * El contenido de la serie --> del mismo tamaño que su indice.
    * `Dataframes`:
        * `pd.DataFrame`, El objeto principal de pandas.
        * Representan una tabla, un tipo de conjutno de datos con un indice asignado a sus filas y uno a sus columnas.
        * Cada fila o columna representa un objeto `pd.Series`

In [5]:
import pandas as pd

In [6]:
pd.__version__

'3.0.6'

## MEtodo `read_csv()`

* `pandas` permite cargar archivos en forma de `DataFrame`.
* Los argumentos de la funcion son **fundamentales**. 
    * Posibles problemas al cargar inadecuadamente un archivo.
* Algunos argumentos de los mas importantes a la hora de la carga de archivos en formato `.csv` son:
    * `path`: Ruta del archivo a cargar.
        * Es el primero en posicion y es **OBLIGATORIO**.
        * Archivos locales y URLs remotas.
    * `sep`: Separador de los elementos del archivo.
    * `header`: Posicion del header.
        * La fila indicada se interpreta como los nombres de las columnas y se cargaran las filas que le precedan.
    * `names`: Nombres a usar para las columnas cargadas.
        * La longitud de esta lista/arreglo debe **coincidir** con el **numero de columnas**
    * `index_col`: Posiciones de las etiquetas usadas como indice.
        * Si es una lista se crea un indice multiple.
        * Si se pasa el valor `False` se puede indicar a pandas que no use la primera columna como el indice del *DataFrame*
    * `usecols`: Subconjunto de las columnas cargadas a usar en la generacion del dataframe
    * `true_values` | `false_values`: Caracteres que seran interpretados como valores de verdad.
    * `skip_rows` | `skip_footer`: FIlas a saltar desde el inicio y desde el final.
    * `nrows`: Total de filas a cargar.
        * Especialmente util para conjuntos de datos grandes donde no nos interese toda la informacion.
    * `na_values` | `keep_default_na` | `na_filter`: Herramientas para el tratamiento d datos faltantes.
        * Muy importante en el proceso de limpieza de datos.
* Ademas de estos existen otros argumentos para la definicion del formato de origen como:
    * fecha
    * numeros decimales
* Esto ofrece variedad de opciones en la lectura de conjuntos de datos.

In [7]:
# Guardamos el dataframe
df_csv = pd.read_csv("msft.csv", sep=",", header=0)

In [8]:
df_csv

         Date   Open   High    Low  Close    Volume  Adj. Close*
0   19-Sep-03  29.76  29.97  29.52  29.96  92433800        29.79
1   18-Sep-03  28.49  29.51  28.42  29.50  67268096        29.34
2   17-Sep-03  28.76  28.95  28.47  28.50  47221600        28.34
3   16-Sep-03  28.41  28.95  28.32  28.90  52060600        28.74
4   15-Sep-03  28.37  28.61  28.33  28.36  41432300        28.20
..        ...    ...    ...    ...    ...       ...          ...
60  25-Jun-03  25.64  25.99  25.14  25.26  60483500        25.12
61  24-Jun-03  25.65  26.04  25.52  25.70  51820300        25.56
62  23-Jun-03  26.14  26.24  25.49  25.78  52584500        25.64
63  20-Jun-03  26.34  26.38  26.01  26.33  86048896        26.18
64  19-Jun-03  26.09  26.39  26.01  26.07  63626900        25.92

[65 rows x 7 columns]

In [17]:
df1 = pd.read_csv("archivo_personas.csv", sep=",", header=None, skiprows=1, names=["nombre_nuevo", "edad_nueva", "ciudad_nueva"])

In [18]:
df1

  nombre_nuevo  edad_nueva ciudad_nueva
0         Juan          25       Madrid
1          Ana          22    barcelona
2        Jhoan          35     Valencia

## Metodo `read_json()`

* Metodo para leer archivos JSON
* Convierte los datos en un DataFrame de pandas

In [21]:
df_json = pd.read_json("mi_json.json")

In [22]:
df_json

        nombre     apellido     cargo  tiene_hijos
0  Pedro Pablo  Perez Perez   docente         True
1         Goku          Son  guerrero         True

In [24]:
df_json.to_csv("datos_json_en_csv.csv", index=False)